### ISSUE TITLE
BOM and position files are  not created in V4.3.0   if checkbox is not pressed.

### ISSUE THREAD

**Issue by imyaFamiliev** [bennymeg/Fabrication-Toolkit#158] opened 2024-04-20 06:04 UTC
Hi!
BOM not created in V4.3.0 (kicad 8.0.1  win 11)  if checkbox for  excluding DNP is not pressed.
In previous plugin version there is no problem , checked 2 weeks ago (there was no checkbox for positions).
Can`t  check exact previous version because it is not appeared in plugin`s install dialog menu :).

**Comment by bennymeg** [comment] 2024-04-20 17:34
Duplicate of #148

**Closed by bennymeg** 2024-04-20 17:34 UTC
Labels: duplicate
